
services:
  flask-app:
    build: .
    container_name: flask-container

    ports:
      - "5000:5000"

    volumes:
      - flask-volume:/app

    restart: always

    environment:
      PYTHONUNBUFFERED: 1

volumes:
  flask-volume:

