# Kubernetes API Version
apiVersion: v1

# Resource Type
kind: ConfigMap

# ConfigMap Information
metadata:

  # ConfigMap Name
  name: hospital-config

# Configuration Data
data:

  # Application Environment
  APP_ENV: production

  # Application Name
  APP_NAME: CarePlus Hospital
