# Kubernetes API Version
apiVersion: v1

# Resource Type
kind: Secret

# Secret Information
metadata:

  # Secret Name
  name: hospital-secret

# Secret Type
type: Opaque

# Secret Data
data:

  # Username in Base64 Format
  username: YWRtaW4=

  # Password in Base64 Format
  password: YWRtaW4xMjM=
